<a href="https://colab.research.google.com/github/shruthikonidala12-arch/mds_lab/blob/main/MDS_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#WEEK 0

In [ ]:
import numpy as np
#Version
print(np.__version__)

2.0.2


In [ ]:
#Creating arrays and basic operations
l1=[20,40,60,80,100]
l2=[2,4,6,8,10]
arr_l1=np.array(l1)
arr_l2=np.array(l2)
print(l1, l2)
print(arr_l1, arr_l2)
print('\nOperations\n')
print(arr_l1+arr_l2)
print(arr_l1-arr_l2)
print(arr_l1*arr_l2)
print(arr_l1/arr_l2)

[20, 40, 60, 80, 100] [2, 4, 6, 8, 10]
[ 20  40  60  80 100] [ 2  4  6  8 10]

Operations

[ 22  44  66  88 110]
[18 36 54 72 90]
[  40  160  360  640 1000]
[10. 10. 10. 10. 10.]


In [ ]:
m=np.array(([1,2,3],[4,5,6]))
m.ndim
#m.dtype
#print(m)

2

In [ ]:
a=np.array(range(100))
a=a.reshape(10,10)
print(a)

[[1. 1.]
 [1. 1.]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### Performance Comparison: Python Lists vs. NumPy Arrays

In [ ]:
%%time
# Squaring elements in a large Python list
size = 10**6 # A large number of elements
python_list = list(range(size))

squared_list = [x**2 for x in python_list]

CPU times: user 43.6 ms, sys: 23 ms, total: 66.5 ms
Wall time: 66.6 ms


In [ ]:
%%time
# Squaring elements in a large NumPy array
import numpy as np
size = 10**6
numpy_array = np.arange(size)

squared_numpy_array = numpy_array**2

CPU times: user 3.27 ms, sys: 1.94 ms, total: 5.2 ms
Wall time: 6.9 ms


#WEEK 1

In [ ]:
#Installing python and checking for numpy
import numpy as np
print(np.__version__)

2.0.2


### Time: List vs Numpy


In [ ]:
%%time
# Squaring elements in a large Python list
size = 10**6 # A large number of elements
python_list = list(range(size))

squared_list = [x**2 for x in python_list]

CPU times: user 65.4 ms, sys: 26.2 ms, total: 91.6 ms
Wall time: 91.4 ms


In [ ]:
%%time
# Squaring elements in a large NumPy array
import numpy as np
size = 10**6
numpy_array = np.arange(size)

squared_numpy_array = numpy_array**2

CPU times: user 2.34 ms, sys: 4.82 ms, total: 7.16 ms
Wall time: 10.5 ms


### Memory Comparison: Python Lists vs. NumPy Arrays

In [ ]:
import sys
import numpy as np

size = 10**6  # Number of elements

# Python list memory usage
python_list_mem = sys.getsizeof(python_list) # already created in previous cells
print(f"Memory occupied by Python list ({size} elements): {python_list_mem / (1024**2):.3f} MB")

# NumPy array memory usage
numpy_array_mem = numpy_array.nbytes # already created in previous cells
print(f"Memory occupied by NumPy array ({size} elements): {numpy_array_mem / (1024**2):.3f} MB")

Memory occupied by Python list (1000000 elements): 7.629 MB
Memory occupied by NumPy array (1000000 elements): 7.629 MB


### Arrays


In [ ]:
lst=[1,2,3,4,5]
type(lst)

list

In [ ]:
arr1=np.array(lst)
print(arr1)

[1 2 3 4 5]


In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr1.ndim

1

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.dtype.name

'int64'

In [ ]:
arr1.size

5

In [ ]:
arr1.shape

(5,)

In [ ]:
arr1.nbytes

40

### Tuples


In [ ]:
t=(1,2,3,4,5,6)

In [ ]:
type(t)

tuple

In [ ]:
t1=(1,)
type(t1)

tuple

In [ ]:
arr2=np.array(t)
print(arr2)

[1 2 3 4 5 6]


In [ ]:
arr2.ndim

1

In [ ]:
import sys
sys.getsizeof(arr2)

160

### Creating NumPy arrays from different Python data structures

In [ ]:
# From a set
python_set = {10, 20, 30, 40}
numpy_from_set = np.array(list(python_set)) # Sets are unordered, convert to list first
print(f"NumPy array from set: {numpy_from_set}")
print(f"Type: {type(numpy_from_set)}")
print(f"Dtype: {numpy_from_set.dtype}")

NumPy array from set: [40 10 20 30]
Type: <class 'numpy.ndarray'>
Dtype: int64


In [ ]:
# From a string
python_string = "hello"
numpy_from_string = np.array(list(python_string)) # Creates an array of characters
print(f"NumPy array from string: {numpy_from_string}")
print(f"Type: {type(numpy_from_string)}")
print(f"Dtype: {numpy_from_string.dtype}")

NumPy array from string: ['h' 'e' 'l' 'l' 'o']
Type: <class 'numpy.ndarray'>
Dtype: <U1


In [ ]:
# From a dictionary (keys, values, or items)
python_dict = {'a': 1, 'b': 2, 'c': 3}

numpy_from_dict_keys = np.array(list(python_dict.keys()))
print(f"NumPy array from dict keys: {numpy_from_dict_keys}")
print(f"Type: {type(numpy_from_dict_keys)}")
print(f"Dtype: {numpy_from_dict_keys.dtype}")

numpy_from_dict_values = np.array(list(python_dict.values()))
print(f"NumPy array from dict values: {numpy_from_dict_values}")
print(f"Type: {type(numpy_from_dict_values)}")
print(f"Dtype: {numpy_from_dict_values.dtype}")

NumPy array from dict keys: ['a' 'b' 'c']
Type: <class 'numpy.ndarray'>
Dtype: <U1
NumPy array from dict values: [1 2 3]
Type: <class 'numpy.ndarray'>
Dtype: int64


In [ ]:
arr3=np.array(t).reshape(2,3)
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr=[[1,2],[3,4]]
mat=np.array(arr)
print(mat)

[[1 2]
 [3 4]]


In [ ]:
mat.ndim

2

In [ ]:
mat.shape

(2, 2)

In [ ]:
mat.size

4

In [ ]:
sys.getsizeof(mat)

160

In [ ]:
mat.reshape(1,4)

array([[1, 2, 3, 4]])

In [ ]:
mat.flatten()

array([1, 2, 3, 4])

In [ ]:
mat.ravel()

array([1, 2, 3, 4])

In [ ]:
arr4=np.array([1,2,3,4])

In [ ]:
print(arr4)

[1 2 3 4]


In [ ]:
arr5=np.array([[1,2],[3,4]])
print(arr5)

[[1 2]
 [3 4]]


In [ ]:
arr6=np.matrix([[1,2],[3,4],[5,6]])
print(arr6)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr7=np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
print(arr7)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [ ]:
arr8=np.arange(1,101)

In [ ]:
print(arr8)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
arr8=np.arange(0,101,2)
print(arr8)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
arr9=np.array(range(100,2))
print(arr9)

[]


In [ ]:
mat2=np.arange(0,10).reshape(5,2)
print(mat2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
mat2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
mat=np.zeros((4,4),dtype='int')
print(mat)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
mat.dtype.name

'int64'

In [ ]:
mat=np.ones((3,3),dtype="int")
print(mat)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
mat=np.full((3,3),3,'int')
print(mat)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [ ]:
id=np.identity(4,'int')
print(id)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a=np.linspace(1,5,3)
print(a)

[1. 3. 5.]


In [ ]:
c=np.random.random((3,3))
print(c)

[[0.14431156 0.03216066 0.52984582]
 [0.61199761 0.5361768  0.26206563]
 [0.96874377 0.90099561 0.56815293]]


In [ ]:
a=np.array((1,2,3,4,5))
a[0]=111
a[2:]=a[2:]*111
print(a)

[111   2 333 444 555]


In [ ]:
a.max()

np.int64(555)

In [ ]:
a.min()

np.int64(2)

#WEEK 2

In [2]:
import numpy as np

print("### NumPy Array Manipulation ###\n")

# 1. Indexing
print("1. Indexing")
arr = np.array([10, 20, 30, 40, 50])
print(f"Original array: {arr}")
print(f"Element at index 0: {arr[0]}")
print(f"Element at last index: {arr[-1]}\n")

# 2. Slicing
print("2. Slicing")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original matrix:\n{matrix}")
print(f"First row: {matrix[0, :]}")
print(f"Last column: {matrix[:, -1]}")
print(f"Sub-array (rows 0-1, cols 1-2):\n{matrix[0:2, 1:3]}\n")

# 3. Reshaping
print("3. Reshaping")
arr_1d = np.arange(12) # 0 to 11
print(f"1D array: {arr_1d}")
arr_2d = arr_1d.reshape(3, 4)
print(f"Reshaped to 3x4:\n{arr_2d}")
arr_flat = arr_2d.flatten() # or .ravel()
print(f"Flattened back to 1D: {arr_flat}\n")

# 4. Joining Arrays
print("4. Joining Arrays")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate along axis 0 (rows) - default
concatenated_arr = np.concatenate((a, b))
print(f"Concatenated (default axis=0): {concatenated_arr}")

c1 = np.array([[1, 2], [3, 4]])
c2 = np.array([[5, 6], [7, 8]])

# Stack vertically (row-wise)
vstacked_arr = np.vstack((c1, c2))
print(f"Vertically stacked:\n{vstacked_arr}")

# Stack horizontally (column-wise)
hstacked_arr = np.hstack((c1, c2))
print(f"Horizontally stacked:\n{hstacked_arr}\n")

# 5. Splitting Arrays
print("5. Splitting Arrays")
split_arr = np.arange(16)
print(f"Original array: {split_arr}")

# Split into 4 equal parts
parts = np.array_split(split_arr, 4)
print(f"Split into 4 parts: {parts}")

# Splitting 2D array
matrix_to_split = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"\nMatrix to split:\n{matrix_to_split}")

# Split horizontally (column-wise) into 2 parts
h_split = np.hsplit(matrix_to_split, 2)
print(f"Horizontal split:\n{h_split[0]}\n{h_split[1]}")

# Split vertically (row-wise) into 3 parts
v_split = np.vsplit(matrix_to_split, 3)
print(f"Vertical split:\n{v_split[0]}\n{v_split[1]}\n{v_split[2]}\n")

print("### Computation on NumPy Arrays ###\n")

# 1. Universal Functions (ufuncs)
print("1. Universal Functions (ufuncs)")
x = np.array([-2, -1, 0, 1, 2])
y = np.array([1, 2, 3, 4, 5])

print(f"Array x: {x}")
print(f"Array y: {y}")
print(f"Absolute values of x: {np.abs(x)}")
print(f"Square root of y: {np.sqrt(y)}")
print(f"Exponential of x: {np.exp(x)}")
print(f"Sine of x: {np.sin(x)}")
print(f"Maximum of x and y: {np.maximum(x, y)}\n")

# 2. Mathematical Methods
print("2. Mathematical Methods")
math_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original array:\n{math_arr}")

print(f"Sum of all elements: {np.sum(math_arr)}")
print(f"Sum along axis 0 (columns): {np.sum(math_arr, axis=0)}") # sum of columns
print(f"Sum along axis 1 (rows): {np.sum(math_arr, axis=1)}")    # sum of rows

print(f"Mean of all elements: {np.mean(math_arr):.2f}")
print(f"Standard deviation: {np.std(math_arr):.2f}")
print(f"Minimum element: {np.min(math_arr)}")
print(f"Maximum element: {np.max(math_arr)}")
print(f"Product of all elements: {np.prod(math_arr)}")

# Dot product
a_dot = np.array([[1, 2], [3, 4]])
b_dot = np.array([[5, 6], [7, 8]])
dot_product = np.dot(a_dot, b_dot)
print(f"\nMatrix A:\n{a_dot}")
print(f"Matrix B:\n{b_dot}")
print(f"Dot product (A.B):\n{dot_product}")

### NumPy Array Manipulation ###

1. Indexing
Original array: [10 20 30 40 50]
Element at index 0: 10
Element at last index: 50

2. Slicing
Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Last column: [3 6 9]
Sub-array (rows 0-1, cols 1-2):
[[2 3]
 [5 6]]

3. Reshaping
1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened back to 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]

4. Joining Arrays
Concatenated (default axis=0): [1 2 3 4 5 6]
Vertically stacked:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacked:
[[1 2 5 6]
 [3 4 7 8]]

5. Splitting Arrays
Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Split into 4 parts: [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]

Matrix to split:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Horizontal split:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
Vertical split:
[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10